---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: sock-shop
readOnlyRootFilesystem: false
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- '*'
users:
- system:admin
- system:cluster-admins
- system:serviceaccount:sock-shop:sock-shop
defaultAddCapabilities:
- CHOWN
- SETGID
- SETUID
- NET_BIND_SERVICE
- DAC_OVERRIDE
- NET_ADMIN
allowedCapabilities:
- CHOWN
- SETGID
- SETUID
- NET_BIND_SERVICE
- DAC_OVERRIDE
- NET_ADMIN
allowHostNetwork: false
allowHostDirVolumePlugin: true
allowHostPID: false
allowHostPorts: false
allowHostIPC: false
seccompProfiles:
- '*'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sock-shop-scc
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["sock-shop"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:sock-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sock-shop-scc
subjects:
- kind: ServiceAccount
  name: sock-shop
  namespace: sock-shop

