---
kind: Service
apiVersion: v1
metadata:
  annotations:
    description: Exposes and load balances the application pods
  name: rocket-chat
spec:
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: rocket-chat
---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of changes in the application image
  name: rocket-chat
spec:
  tags:
  - annotations:
      openshift.io/imported-from: docker.io/rocketchat/rocket.chat:0.63.3
    from:
      kind: DockerImage
      name: docker.io/rocketchat/rocket.chat:0.63.3
    name: 0.63.3
---
apiVersion: v1
kind: Route
metadata:
  name: rocket-chat
spec:
  to:
    kind: Service
    name: rocket-chat
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    app: rocket-chat
  name:  rocket-chat
spec:
  replicas: 1
  selector:
    app: rocket-chat
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: rocket-chat
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://mongodb_user:mongodb_password@mongodb:27017/mongodb
        image: ' '
        name:  rocket-chat
        ports:
          - containerPort: 3000
            protocol: TCP
        volumeMounts:
        - mountPath: /app/uploads
          name: rocketchat-volume-1
      volumes:
      - emptyDir: {}
        name: rocketchat-volume-1
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - rocket-chat
      from:
        kind: ImageStreamTag
        name: "rocket-chat:0.63.3"
        namespace: "rocket-chat"
    type: ImageChange
  - type: ConfigChange
