---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: online-boutique
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 300m
  behavior:
    scaleDown: 
      policies: 
      - type: Pods 
        value: 1
        periodSeconds: 60 
      selectPolicy: Min 
      stabilizationWindowSeconds: 300 
    scaleUp: 
      policies:
      - type: Pods
        value: 1 
        periodSeconds: 60
      selectPolicy: Max
      stabilizationWindowSeconds: 0

