bases:
  - ../../base

patchesJson6902:
- target:
    version: v1
    kind: Route
    name: frontend
  patch: |-
    - op: replace
      path: /spec/host
      value: online-boutique.mauro.emeatam.support
