---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
        app.kubernetes.io/name: netshoot
        app.kubernetes.io/version: "0.1"
        app.kubernetes.io/component: netshoot
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: nicolaka/netshoot
        command:
        - "sleep"
        - "infinity"
        env:
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
